# Generated by Django 5.1 on 2024-10-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeBlog', '0002_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
    ]
