# Generated by Django 5.1 on 2024-10-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeBlog', '0003_alter_comentario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.CharField(max_length=200, verbose_name='Contenido'),
        ),
    ]
