# Generated by Django 5.1 on 2024-10-16 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeBlog', '0004_alter_comentario_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='titulo',
        ),
    ]
